language: cpp
compiler:
  - gcc
  - clang

env:
  global:
    BUILD_DIR=build

script:
  - make BUILD_DIR=${BUILD_DIR} tests
  - (cd ${BUILD_DIR}/tests/ && ./MainTest)  
  - make BUILD_DIR=${BUILD_DIR} examples

